const mongoose = require('mongoose');

// Define the schema for storing Twitter-like posts and replies
const DatabaseSchema = new mongoose.Schema(
  {
    id: { type: String, required: true }, 
    profilePic: { type: String, required: true },          // The tweet or post itself
    date: { type: Date, default: Date.now },         // The date the post was created
    name: { type: String, required: true },        // The user ID of the person who posted it
    handle: { type: String, default: "" },               // Change to String to store UUID or other identifiers
    tweet: { type: String, default: "" },            // Optional image URL associated with the post
    replies: { type: String, default: "" } ,                              // Array to store sarcastic replies generated by the system
    replyde: { type: [String], default: [] },
  },
  {
    collection: 'NotATwitter',                           // MongoDB collection name
    timestamps: true                                 // Automatically manage createdAt and updatedAt fields
  }
);

// Export the model for usage in the main application
module.exports = mongoose.model('Database', DatabaseSchema);
